### ISSUE TITLE
In Get Started section, the first two links don't work correctly, it launch 404 error

### ISSUE THREAD

**Issue by AlexRToledo** [sherpon/community#3]
Links:
https://community.sherpon.com/docs/guides/get-started/create-project
https://community.sherpon.com/docs/guides/get-started/get-subscription-plans

**Comment by brucegroverlee** [comment]
let me fix that. Thx!

**Comment by brucegroverlee** [comment]
I changed the content of the **Get started** page https://community.sherpon.com/docs/guides/get-started/. 

So, the new urls are:
- https://community.sherpon.com/docs/guides/create-project/
- https://community.sherpon.com/docs/guides/get-subscription-plans/
